export interface Unit {
    name: string;
    address: string;
    cep?: string;
    type: 'Própria' | 'Parceria';
    region: 'Região Sudeste' | 'Região Sul' | 'Região Nordeste' | 'Região Centro-Oeste' | 'Região Norte';
    state: string;
    hasRoom: boolean;
    status: 'Ativo' | 'Inativo' | 'Desativada';
    launchYear: string | number;
    // Extended fields for 'Ficha Técnica'
    complement?: string;
    condo?: string;
    contractStart?: string;
    gracePeriod?: string;
    rent?: string;
    iptu?: string;
    insurance?: string;
    hasMessenger?: boolean;
    mailboxRequired?: boolean;
}

export const units: Unit[] = [
    // --- PARCERIAS (ATIVAS) ---
    {
        name: 'Belém (PA)',
        address: 'R. Avertano Rocha, 192, Campina, Belém - PA',
        cep: '66023-120',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'PA',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Salas Comerciais',
        condo: 'Edifício Do It Coworking',
        contractStart: '20/05/2022',
        hasMessenger: true
    },
    {
        name: 'Brasília 2 (DF)',
        address: 'V W3, SCR/SUL, Quadra 516, Bloco B, no 69, Pavimento Superior, Asa Sul, Brasília - DF',
        cep: '70381-525',
        type: 'Parceria',
        region: 'Região Centro-Oeste',
        state: 'DF',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Pavimento Superior',
        condo: 'BSB Coworking',
        contractStart: '09/08/2022',
        hasMessenger: true
    },
    {
        name: 'Cascavel (PR)',
        address: 'R Presidente Kennedy, 481, Centro, Cascavel - PR',
        cep: '85810-040',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'PR',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'Omni Coworking',
        contractStart: '06/12/2022',
        hasMessenger: true
    },
    {
        name: 'Itajaí (SC)',
        address: 'Rua Olímpio Miranda Junior, no 168, Sala 10 e 11, Centro, Itajaí - SC',
        cep: '88301-080',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'SC',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 10 e 11',
        condo: 'Gaia Coworking',
        contractStart: '07/11/2022',
        hasMessenger: true
    },
    {
        name: 'João Pessoa (PB)',
        address: 'Avenida Dom Pedro I, no 719, sala 104, Tambiá, João Pessoa – PB',
        cep: '58020-514',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'PB',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 104',
        condo: 'Tesla Office',
        contractStart: '10/10/2022',
        mailboxRequired: true
    },
    {
        name: 'Joinville (SC)',
        address: 'Rua Armando Andrade, no 97, Bom Retiro, Joinville - SC',
        cep: '89223-066',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'SC',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'Time Coworking',
        contractStart: '28/10/2022'
    },
    {
        name: 'Jundiaí (SP)',
        address: 'Rua Anchieta, no 204, Sala 102 e 107, Vila Boaventura, Jundiaí - SP',
        cep: '13201-804',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        complement: 'Sala 102 e 107',
        condo: 'Easy 2 Work',
        contractStart: '15/02/2023'
    },
    {
        name: 'Macapá (AP)',
        address: 'Av. dos Caramuru, 1293-A - Buritizal, Macapá - AP',
        cep: '68902-863',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'AP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'Cocar Coworking',
        contractStart: '09/05/2022'
    },
    {
        name: 'Maceió (AL)',
        address: 'Av Fernandes Lima, no 8, andar 4, sala 418 e 419, Farol, Maceió - AL',
        cep: '57055-000',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'AL',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Andar 4 - Sala 418/419',
        condo: 'NEO Coworking',
        contractStart: '02/09/2022',
        hasMessenger: true
    },
    {
        name: 'Montes Claros (MG)',
        address: 'Rua Padre Augusto, n 16, Sala 302, Centro, Montes Claros - MG',
        cep: '39400-053',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'MG',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        complement: 'Sala 302',
        condo: 'Mutua Coworking',
        contractStart: '24/02/2023'
    },
    {
        name: 'Palmas (TO)',
        address: 'Q ACSV SE 32 AV LO 05, no 22, Plano Diretor Sul, Palmas - TO',
        cep: '77021-026',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'TO',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'Très Criative',
        contractStart: '27/10/2022'
    },
    {
        name: 'Porto Velho (RO)',
        address: 'Av Sete de Setembro, 1925, Porto Velho - RO',
        cep: '76.804-123',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'RO',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2020,
        condo: 'Hub Coworking',
        contractStart: '28/06/2022'
    },
    {
        name: 'Rio Branco (AC)',
        address: 'Rua Floriano Peixoto, 883, Centro, Rio Branco - AC',
        cep: '69.900-090',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'AC',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'CNC Coworking',
        contractStart: '25/07/2022'
    },
    {
        name: 'São José (SC)',
        address: 'Rua Alvaro Tolentino, no 30, Campinas, São José - SC',
        cep: '88.101-240',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'SC',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        condo: 'Up Working',
        contractStart: '10/02/2023'
    },
    {
        name: 'São José dos Campos (SP)',
        address: 'Av. Alfredo Ignácio Nogueira Penido, 335, Ed. Madison Tower, Sala 706, São José dos Campos - SP',
        cep: '12246-000',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 706',
        condo: 'WeShare Escritórios Compartilhados',
        contractStart: '03/11/2022'
    },
    {
        name: 'Uberlândia (MG)',
        address: 'Av Doutor Jaime Ribeiro da Luz, no 971, sala 52, Santa Monica, Uberlândia - MG',
        cep: '38.408-188',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'MG',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 52',
        condo: 'Virtual Espaço Executivo',
        contractStart: '07/11/2022'
    },
    {
        name: 'Vitória (ES) - Parceria',
        address: 'Avenida Nossa Senhora da Penha, 2598, Santa Luiza, Vitória - ES',
        cep: '29.045-402',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'ES',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        condo: 'Villa Empresarial Coworking',
        contractStart: '01/08/2022'
    },

    // --- UNIDADES PRÓPRIAS (ATIVAS) ---
    {
        name: 'Alphaville (SP)',
        address: 'Alameda Rio Negro, 503, Sala 2020-A, Alphaville Industrial, Barueri - SP',
        cep: '06454-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2019,
        complement: 'Sala 2020',
        condo: 'Edifício Escritórios Rio Negro',
        contractStart: '16/12/2019',
        gracePeriod: '1 mês',
        rent: 'R$ 2.000,00',
        iptu: 'Não informado',
        insurance: 'Sim'
    },
    {
        name: 'Belo Horizonte (MG)',
        address: 'Rua Rio Grande do Norte, 1435, Sala 708, Funcionários, Belo Horizonte - MG',
        cep: '30130-131',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'MG',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 708',
        condo: 'Edifício Savassi Premium',
        contractStart: '27/08/2020',
        gracePeriod: '3 meses',
        rent: 'R$ 2.070,00',
        insurance: 'Sim'
    },
    {
        name: 'Berrini (SP)',
        address: 'Av. Engenheiro Luiz Carlos Berrini, 1748, Sala 1710, Cidade Monções, São Paulo - SP',
        cep: '04571-010',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 1710',
        condo: 'Edifício E-Office Design Berrini',
        contractStart: '13/02/2020',
        gracePeriod: '1 mês',
        rent: 'R$ 2.500,00',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'Campinas (SP)',
        address: 'Rua Comendador Torlogo Dauntre, 74, Sala 1207, Cambuí, Campinas - SP',
        cep: '13025-270',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 1207',
        condo: 'Helbor Offices Norte Sul',
        contractStart: '20/08/2020',
        rent: 'R$ 2.100,00',
        insurance: 'Sim'
    },
    {
        name: 'Campinas (Av. José de Sousa Campos) (SP)',
        address: 'Av. José de Sousa Campos, 1073, Sala 1207, Cambuí, Campinas - SP',
        cep: '13025-270',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 1207',
        condo: 'Helbor Offices Norte Sul',
        contractStart: '20/08/2020',
        rent: 'R$ 2.100,00',
        insurance: 'Sim'
    },
    {
        name: 'Campo Grande (MS)',
        address: 'Av Afonso Pena, 4785, Sala 701, Campo Grande - MS',
        cep: '79031-010',
        type: 'Própria',
        region: 'Região Centro-Oeste',
        state: 'MS',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 701',
        condo: 'The Place Corporate - Torre 1',
        contractStart: '01/11/2021',
        rent: 'R$ 2.600,00',
        insurance: 'Sim'
    },
    {
        name: 'Curitiba (PR)',
        address: 'Praça São Paulo da Cruz, 50, Sala 1904, Centro, Curitiba - PR',
        cep: '80030-480',
        type: 'Própria',
        region: 'Região Sul',
        state: 'PR',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 1904',
        condo: 'Edificio AR 3000',
        contractStart: '01/08/2020',
        gracePeriod: '3 meses',
        rent: 'R$ 3.000,00',
        iptu: 'R$ 182,68',
        insurance: 'Sim'
    },
    {
        name: 'Curitiba (Juvevê) (PR)',
        address: 'Rua Bom Jesus, 212, Sala 1904, Juvevê, Curitiba - PR',
        cep: '80.035-010',
        type: 'Própria',
        region: 'Região Sul',
        state: 'PR',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 1904',
        condo: 'Edificio AR 3000',
        contractStart: '01/08/2020',
        gracePeriod: '3 meses',
        rent: 'R$ 3.000,00',
        iptu: 'R$ 182,68',
        insurance: 'Sim'
    },
    {
        name: 'Faria Lima 1 (SP)',
        address: 'Av. Brig. Faria Lima, 2369, Conj. 1102 e 1103, Jardim Paulistano, São Paulo - SP',
        cep: '01452-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2018,
        complement: 'Conj. 1102 e 1103',
        condo: 'Edificio Barão de Iguatemi',
        contractStart: '01/03/2018',
        gracePeriod: '2 meses',
        rent: 'R$ 2.282,41',
        iptu: 'R$ 205,86',
        insurance: 'Sim'
    },
    {
        name: 'Faria Lima 2 (SP)',
        address: 'Avenida Brigadeiro Faria Lima, 1811, Sala 1119 e 1120, Jardim Paulistano, São Paulo - SP',
        cep: '01452-001',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 1119 e 1120',
        condo: 'Edifício CEPAVI',
        contractStart: '25/05/2022',
        rent: 'R$ 2.400,00',
        iptu: 'R$ 373,00',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'Florianópolis (SC)',
        address: 'Av. Pref. Osmar Cunha, 416, Sala 1108, Centro, Florianópolis - SC',
        cep: '88015-100',
        type: 'Própria',
        region: 'Região Sul',
        state: 'SC',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 1108',
        condo: 'Edifício Koerich Empresarial Rio Branco',
        contractStart: '03/05/2021',
        rent: 'R$ 2.800,00',
        iptu: 'R$ 1.455,68',
        hasMessenger: true
    },
    {
        name: 'Fortaleza (CE)',
        address: 'Rua Monsenhor Bruno, 1153, Sala 1423, Fortaleza - CE',
        cep: '60115-191',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'CE',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 1423',
        condo: 'SCOPA PLATINUM CORPORATE',
        contractStart: '10/10/2021',
        rent: 'R$ 1.550,00',
        iptu: 'R$ 104,62',
        insurance: 'Sim'
    },
    {
        name: 'Goiânia (GO)',
        address: 'Av. Portugal, 1148, Sala C 2501, Setor Marista, Goiânia - GO',
        cep: '74150-030',
        type: 'Própria',
        region: 'Região Centro-Oeste',
        state: 'GO',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala C 2501',
        condo: 'Edifício Órion Business & Health Complex',
        contractStart: '02/12/2020',
        rent: 'R$ 4.000,00',
        iptu: 'R$ 150,00',
        insurance: 'Sim'
    },
    {
        name: 'Guarulhos (SP)',
        address: 'Av. Salgado Filho, 2120, Sala 2112, Torre C, Guarulhos - SP',
        cep: '07115-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 2112 - Torre C',
        condo: 'Condomínio Via Alameda',
        contractStart: '21/09/2021',
        gracePeriod: '1 mês',
        rent: 'R$ 2.000,00',
        iptu: 'R$ 95,57',
        insurance: 'Sim'
    },
    {
        name: 'Paulista 1 (SP)',
        address: 'Avenida Paulista, 171, 4º andar, Bela Vista, São Paulo - SP',
        cep: '01311-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Inativo',
        launchYear: 2017,
        complement: '4º andar',
        condo: 'Edifício D. Pedro I de Alcântara',
        contractStart: '15/05/2017',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'Paulista 2 (SP)',
        address: 'Avenida Paulista, 1636, Conj. 1504, Cerqueira Cesar, São Paulo - SP',
        cep: '01310-200',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Conj. 1504',
        condo: 'Paulista Corporate',
        contractStart: '29/10/2020',
        rent: 'R$ 2.600,00',
        iptu: 'R$ 622,28',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'Porto Alegre (RS)',
        address: 'Avenida Carlos Gomes, 700, Sala 606, Auxiliadora, Porto Alegre - RS',
        cep: '90480-000',
        type: 'Própria',
        region: 'Região Sul',
        state: 'RS',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 606',
        condo: 'Edifício Platinum Tower',
        contractStart: '05/10/2020',
        gracePeriod: '3 meses',
        rent: 'R$ 3.400,00',
        iptu: 'R$ 250,00',
        insurance: 'Sim'
    },
    {
        name: 'Recife (PE)',
        address: 'Avenida República do Líbano, 251, Sala 2205, Torre A, Recife - PE',
        cep: '51110-160',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'PE',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 2205 - Torre A',
        condo: 'Empresarial Rio Mar Trade Center',
        contractStart: '10/08/2021',
        gracePeriod: '1 mês',
        rent: 'R$ 3.323,18',
        iptu: 'R$ 396,30',
        insurance: 'Sim'
    },
    {
        name: 'Rio de Janeiro 2 (RJ)',
        address: 'Rua Visconde de Pirajá, 414, Sala 718, Ipanema, Rio de Janeiro - RJ',
        cep: '22410-002',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'RJ',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 718',
        condo: 'Edificio Quartier Ipanema',
        contractStart: '01/08/2020',
        gracePeriod: '3 meses',
        rent: 'R$ 2.400,00',
        iptu: 'R$ 502,50',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'Salvador (BA)',
        address: 'Av Tancredo Neves, 2539, Sala 2609, Londres, Salvador - BA',
        cep: '41820-021',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'BA',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 2609 - Torre Londres',
        condo: 'CEO Salvador Shopping',
        contractStart: '02/02/2021',
        gracePeriod: '1 mês',
        rent: 'R$ 2.000,00',
        iptu: 'R$ 272,66',
        insurance: 'Sim',
        hasMessenger: true
    },
    {
        name: 'São Bernardo do Campo (SP)',
        address: 'Rua José Versolato, 111, Sala 3102 - Bloco B, Centro, São Bernardo do Campo - SP',
        cep: '09750-730',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2020,
        complement: 'Sala 3102 - Bloco B',
        condo: 'Edificio Domo Corporate',
        contractStart: '08/09/2020',
        gracePeriod: '12 meses',
        rent: 'R$ 1.200,00',
        insurance: 'Sim'
    },
    {
        name: 'Sorocaba (SP)',
        address: 'Rua Raphael Dias da Silva, 75, Sala 605, Campolim, Sorocaba - SP',
        cep: '18048-120',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2022,
        complement: 'Sala 605',
        condo: 'Edifício West Point',
        contractStart: '23/03/2022',
        rent: 'R$ 2.000,00',
        iptu: 'R$ 94,33',
        insurance: 'Sim'
    },
    {
        name: 'Tatuapé (SP)',
        address: 'Rua Serra de Botucatu, 878, Sala 1503, Tatuapé, São Paulo - SP',
        cep: '03317-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2021,
        complement: 'Sala 1503',
        condo: 'Higgs Empresarial',
        contractStart: '08/11/2021',
        rent: 'R$ 2.350,00',
        iptu: 'R$ 230,00',
        insurance: 'Sim'
    },
    {
        name: 'Verbo Divino (SP)',
        address: 'Rua Verbo Divino, 2001, Sala 305 - Torre B, Chácara Santo Antônio, São Paulo - SP',
        cep: '04719-002',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2017,
        complement: 'Sala 305 - Torre B',
        condo: 'Empreendimento EENU',
        contractStart: '01/08/2017',
        insurance: 'Sim'
    },
    {
        name: 'Vila Leopoldina (SP)',
        address: 'Av. Mofarrej, 348, Sala 1308, Vila Leopoldina, São Paulo - SP',
        cep: '05311-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2015,
        complement: 'Sala 1308',
        condo: 'Upper Office',
        contractStart: '13/07/2015',
        rent: 'R$ 2.752,00',
        insurance: 'Sim'
    },

    // --- RECENT LANUNCHES & MISSING PORTFOLIO (2023-2026) ---
    {
        name: 'Lauro de Freitas (BA)',
        address: 'Av Praia de Pajussara, no 294, Vilas do Atlântico, Lauro de Freitas - BA',
        cep: '42.708-720',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'BA',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        condo: 'Station Coworking',
        contractStart: '20/06/2023'
    },
    {
        name: 'Maringá (PR)',
        address: 'Avenida Dr. Luiz Teixeira Mendes, 3096 - Zona 05, Maringá - PR',
        cep: '87015-001',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'PR',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        condo: 'Cometogether Coworking',
        contractStart: '14/05/2024'
    },
    {
        name: 'Aracaju 2 (SE)',
        address: 'Rua Riachuelo, 1200, São José, Aracaju - SE',
        cep: '49015-160',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'SE',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        condo: 'Conviva Coworking',
        contractStart: '11/09/2023'
    },
    {
        name: 'São Luís (MA)',
        address: 'Av. Cel. Colares Moreira, 444, Sala 649B, 6° andar, Jardim Renascença, São Luís - MA',
        cep: '65075-441',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'MA',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        complement: 'Sala 649B - Andar 6',
        condo: 'Ed. Monumental / São Luís Coworking',
        contractStart: '13/11/2023'
    },
    {
        name: 'Niterói (RJ)',
        address: 'Estr. Francisco da Cruz Nunes, 5982, Sala 204, Piratininga, Niterói - RJ',
        cep: '24350-190',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'RJ',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        complement: 'Sala 204',
        condo: 'Redes Coworking',
        contractStart: '13/11/2023'
    },
    {
        name: 'Assis (SP)',
        address: 'Rua Mauri Torreti, 60, Portal São Francisco, Assis - SP',
        cep: '19807-466',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        condo: 'DCPHouse',
        contractStart: '25/08/2023'
    },
    {
        name: 'Cuiabá (MT)',
        address: 'Rua Tiradentes, 220, Bairro Pico Do Amor, Cuiabá - MT',
        cep: '78065-075',
        type: 'Parceria',
        region: 'Região Centro-Oeste',
        state: 'MT',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2023,
        condo: 'Coworking Pantanal',
        contractStart: '12/12/2023'
    },
    {
        name: 'Paulista 3 (SP) - MEV',
        address: 'Av. Paulista, 726, Sala 1202, Bela Vista, São Paulo - SP',
        cep: '01310-200',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        complement: 'Sala 1202',
        condo: 'Edificio Palácio 5ª Avenida',
        contractStart: '25/04/2024',
        rent: 'R$ 3.400,00',
        iptu: 'R$ 353,71',
        hasMessenger: true
    },
    {
        name: 'Olinda (PE)',
        address: 'Avenida Presidente Getúlio Vargas, 1605, loja 09, Olinda - PE',
        cep: '53.030-010',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'PE',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        complement: 'Loja 09 - CX Postal 57',
        condo: 'Jardim Coworking',
        contractStart: '21/06/2024'
    },
    {
        name: 'Manaus (AM)',
        address: 'Rua Diamante, 278, Nossa Senhora das Graças, Manaus - AM',
        cep: '69053-030',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'AM',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        condo: 'Integra Coworking',
        contractStart: '10/07/2024'
    },
    {
        name: 'Caruaru 2 (PE)',
        address: 'Rua Artur Antônio da Silva, S/N, Sala 1901, Universitário, Caruaru - PE',
        cep: '55016-445',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'PE',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        complement: 'Sala 1901',
        condo: 'Empresarial Nordeste Corporate',
        contractStart: '22/08/2024',
        rent: 'R$ 3.000,00',
        iptu: 'R$ 130,00',
        hasMessenger: true
    },
    {
        name: 'Anápolis (GO)',
        address: 'Avenida Cerejeiras, S/N, Quadra 17, Lote 08, Residencial Cerejeiras, Anápolis - GO',
        cep: '75097-154',
        type: 'Parceria',
        region: 'Região Centro-Oeste',
        state: 'GO',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        condo: 'Guarde Mais',
        contractStart: '03/10/2024'
    },
    {
        name: 'Blumenau (SC)',
        address: 'Rua 15 de novembro, 727, 2º andar - Centro, Blumenau - SC',
        cep: '89.010-001',
        type: 'Parceria',
        region: 'Região Sul',
        state: 'SC',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2025,
        complement: '2º andar',
        condo: "XV Office's",
        contractStart: '26/08/2025'
    },
    {
        name: 'Ribeirão Preto 2 (SP)',
        address: 'Avenida Doutor Plínio de Castro Prado, 288, Sala 23, Jardim Palma Travassos, Ribeirão Preto - SP',
        cep: '14091-170',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2025,
        complement: 'Sala 23',
        condo: 'Paulista Office',
        contractStart: '12/08/2025',
        rent: 'R$ 1.800,00',
        iptu: 'R$ 51,79',
        hasMessenger: true
    },
    {
        name: 'Brasília 3 (DF)',
        address: 'SHIS QI 07, Bloco B, Sala 201, Lago Sul, Brasília - DF',
        cep: '71615-720',
        type: 'Parceria',
        region: 'Região Centro-Oeste',
        state: 'DF',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2024,
        complement: 'Sala 201 - Bloco B',
        condo: 'BSB Coworking',
        contractStart: '24/11/2024'
    },
    {
        name: 'Santos (SP)',
        address: 'Avenida Ana Costa, nº 61, Térreo, Gonzaga, Santos - SP',
        cep: '11.060-001',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Ativo',
        launchYear: 2025,
        complement: 'Térreo',
        condo: 'Espaço Certo',
        contractStart: '05/11/2025'
    },
    {
        name: 'Natal 3 (RN)',
        address: 'Avenida Amintas Barros, 3700, sala 708 bl A, Natal - RN',
        cep: '59075-810',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'RN',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2026,
        complement: 'Sala 708 Bloco A',
        condo: 'CTC - Corporate Tower Center',
        contractStart: '02/01/2026',
        rent: 'R$ 2.400,00',
        iptu: 'R$ 298,00',
        hasMessenger: true
    },
    {
        name: 'Brasília 4 (DF)',
        address: 'SGAS 915, Bloco D, Sala 103, Asa Sul, Brasília - DF',
        cep: '70390-150',
        type: 'Própria',
        region: 'Região Centro-Oeste',
        state: 'DF',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2025,
        complement: 'Sala 103',
        condo: 'Unidade própria',
        contractStart: '17/06/2025',
        rent: 'R$ 1.400,00',
        iptu: 'R$ 343,02',
        hasMessenger: true
    },
    {
        name: 'Paulista 4 (SP)',
        address: 'Av Paulista, 91, Conj 905, São Paulo - SP',
        cep: '01311-000',
        type: 'Própria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2026,
        complement: 'Conjunto 905',
        condo: 'Paulista Tower',
        contractStart: '02/02/2026',
        rent: 'R$ 4.500,00',
        iptu: 'R$ 1.520,00',
        hasMessenger: true
    },
    {
        name: 'Teresina 2 (PI)',
        address: 'Avenida Universitária, N.º750, Sala 1114, Teresina - PI',
        cep: '64049-494',
        type: 'Própria',
        region: 'Região Nordeste',
        state: 'PI',
        hasRoom: true,
        status: 'Ativo',
        launchYear: 2026,
        complement: 'Sala 1114',
        condo: 'Diamond Center, Torre Office Tower',
        contractStart: '10/02/2026',
        rent: 'R$ 3.000,00',
        iptu: 'Não informado',
        hasMessenger: true
    },

    // --- UNIDADES DESATIVADAS (HISTÓRICO ÚTIL PARA COMERCIAL/RETENÇÃO) ---
    {
        name: 'Aracaju 1 (SE)',
        address: 'R LAGARTO, 1624, SAO JOSE, Aracaju - SE',
        cep: '49015-270',
        type: 'Parceria',
        region: 'Região Nordeste',
        state: 'SE',
        hasRoom: false,
        status: 'Desativada',
        launchYear: 2022,
        condo: 'Nexus Escritórios Compartilhados',
        contractStart: '20/05/2022'
    },
    {
        name: 'Boa Vista (RR)',
        address: 'Avenida General Ataíde Teive, n° 832, Mecejana, Boa Vista - RR',
        cep: '69304-360',
        type: 'Parceria',
        region: 'Região Norte',
        state: 'RR',
        hasRoom: false,
        status: 'Desativada',
        launchYear: 2023,
        condo: '832 Work',
        contractStart: '11/07/2023'
    },
    {
        name: 'Brasília 1 (DF)',
        address: 'Quadra 701 Bloco O - Asa Sul, Brasília - DF',
        cep: '70340-000',
        type: 'Parceria',
        region: 'Região Centro-Oeste',
        state: 'DF',
        hasRoom: false,
        status: 'Desativada',
        launchYear: 2021,
        condo: 'Edifício Centro Multiempresarial'
    },
    {
        name: 'Osasco (SP)',
        address: 'Av dos Autonomistas, no 896, Anexo 900, Bloco Santorini, cj. 1209, Vila Yara, Osasco - SP',
        cep: '06.020-010',
        type: 'Parceria',
        region: 'Região Sudeste',
        state: 'SP',
        hasRoom: false,
        status: 'Desativada',
        launchYear: 2023,
        condo: 'Apis Coworking',
        contractStart: '30/01/2023'
    }
];
